Bump to 1.66 because `marker_api` uses the feature from there.
```
error[E0658]: custom discriminant values are not allowed in enums with tuple or struct variants
```