Replace bors with Github native merge queue (#222)
* Replace bors with Github native merge queue

* Try using `1.65.0` for compiling cargo-marker, but `1.71.1` for cargo fmt

* Add more comments

* Bump to 1.66 because `marker_api` uses the feature from there.

```
error[E0658]: custom discriminant values are not allowed in enums with tuple or struct variants
```

* Remove `split-debuginfo` to support an older version of rust toolchain